### ISSUE TITLE
OSS audio

### ISSUE THREAD

**Issue by coypoop** [mozilla/cubeb#230]
Hi!

I've been running latest firefox on NetBSD 7.99.59 with patches to restore removed support for OSS*. It works well for me.
Would it be welcome? I can amend them as needed.
Asking first - I know it was previously removed.
I'm not too sure how to run the tests or use cubeb standalone, though.

*- compat library, not OSSv4 proper.

**Comment by kinetiknz** [comment]
Patches and ongoing support for backends is definitely welcome.

OSS is in a strange state where we've had two implementations contributed some time ago (https://github.com/kinetiknz/cubeb/pull/41 and https://bugzilla.mozilla.org/show_bug.cgi?id=1021761) and never reached a point of agreement where one or the other (or some combination) could be merged.  It'd be good to resolve that, somehow, so we at least have a single point for further contributions to OSS support.

Which implementation are your patches based on?

**Comment by coypoop** [comment]
Good to hear! I didn't know the status of it.
I've actually independently made a fix to the 'cracking on youtube videos' mentioned on that mozilla bug report, which is how I felt like I know enough about the code to request merging it (still feels strange).
I've used the one on bugzilla since I only knew of it, but didn't know where it came from (it was a patch to a package manager.
I imagine the other folk will be happy so long as they have something merged, it can always be worked on :-)

**Comment by hselasky** [comment]
Hi,

I'd like to see https://github.com/mozilla/cubeb/commit/fa0645fed9d2fa8dfbcf911812d6708c806e67b3 upstreamed to Firefox. It fixes some issues "crackling issues" with video conferencing. I currently checked Firefox 90, and the cubeb code lags a bit :-)

@coypoop: Is this issue resolved?

--HPS

**Comment by kinetiknz** [comment]
> I'd like to see [fa0645f](https://github.com/mozilla/cubeb/commit/fa0645fed9d2fa8dfbcf911812d6708c806e67b3) upstreamed to Firefox. It fixes some issues "crackling issues" with video conferencing. I currently checked Firefox 90, and the cubeb code lags a bit :-)

Thanks for the ping.  That change should already be in Firefox 90, landed via the cubeb update in https://bugzilla.mozilla.org/show_bug.cgi?id=1712621.

**Comment by coypoop** [comment]
Thanks!

**Comment by hselasky** [comment]
@kinetiknz : Thank you! 

Firefox 90.0a1, so I'll just wait for 90.1 .

**Comment by hselasky** [comment]
Just got 90.0.1. One observation:

The two following paths are out of sync. Not sure if it matters:

firefox-90.0.1/third_party/rust/cubeb-sys/libcubeb/src/cubeb_oss.c
firefox-90.0.1/media/libcubeb/src/cubeb_oss.c

firefox-90.0.1.source.tar.xz

**Comment by kinetiknz** [comment]
> The two following paths are out of sync. Not sure if it matters:
> 
> firefox-90.0.1/third_party/rust/cubeb-sys/libcubeb/src/cubeb_oss.c
> firefox-90.0.1/media/libcubeb/src/cubeb_oss.c

media/libcubeb is the version that is compiled into Gecko.  third_party/rust/cubeb-sys is included in the source as part of Rust crate vendoring, but isn't compiled in.  third_party/rust/cubeb-sys will update from time to time as the cubeb-rs crate updates, but it's not a problem for it to be slightly out of sync.
