### ISSUE TITLE
Stop audio client after draining

### ISSUE THREAD

**Issue by kinetiknz** [mozilla/cubeb#366]
If I understand https://bugzilla.mozilla.org/show_bug.cgi?id=1319565 correctly, we should call Stop() on our audio client when draining completes to avoid causing underrun events in the audio server.  Our current behaviour leaves the audio client running but stops querying it, and it will eventually be stopped when the caller stops and/or destroys the stream.

**Comment by zamaudio** [comment]
#154 might be fixed if this issue is resolved.

**Comment by zamaudio** [comment]
How about this patch? It seems to fix #154 :+1:
```
diff --git a/dom/media/AudioStream.cpp b/dom/media/AudioStream.cpp
index ce6fb2f3bc8d..82d6197bd78f 100644
--- a/dom/media/AudioStream.cpp
+++ b/dom/media/AudioStream.cpp
@@ -475,6 +475,8 @@ AudioStream::Shutdown()
     MonitorAutoUnlock mon(mMonitor);
     // Force stop to put the cubeb stream in a stable state before deletion.
     cubeb_stream_stop(mCubebStream.get());
+    // Destroy the active stream
+    cubeb_stream_destroy(mCubebStream.get());
     // Must not try to shut down cubeb from within the lock!  wasapi may still
     // call our callback after Pause()/stop()!?! Bug 996162
     mCubebStream.reset();
```

**Comment by zamaudio** [comment]
No, above crashes the tab :(

**Comment by kinetiknz** [comment]
#154 is not related.
