### ISSUE TITLE
Use system speex when available

### ISSUE THREAD

**Issue by Tachi107** [mozilla/cubeb#658]
Hi, this is related to #657. I was looking into how to compile cubeb using the speex library already installed on my system, but I don't fully understand how it is being used by this project. 

It is not simply being linked with the `cubeb` target, but it seems that it's compiled together with it (?)
https://github.com/mozilla/cubeb/blob/6ce95962c8bb1442a725cbacdc77d5d8cbce43ad/CMakeLists.txt#L76

I'm not super experienced with CMake (I use Meson when possible), so could you please tell me if using system speex is possible? Why isn't is treated as a normal dependency (with `target_link_libraries()`)?

Thanks

**Comment by padenot** [comment]
It's indeed vendored. This makes libcubeb standalone, which is nice, especially on OSes where the package manager doesn't exist.

It used to be that we'd carry patch on it but not anymore it seems like.

**Comment by kinetiknz** [comment]
> Hi, this is related to #657. I was looking into how to compile cubeb using the speex library already installed on my system, but I don't fully understand how it is being used by this project.
> 
> It is not simply being linked with the `cubeb` target, but it seems that it's compiled together with it (?)
> 
> https://github.com/mozilla/cubeb/blob/6ce95962c8bb1442a725cbacdc77d5d8cbce43ad/CMakeLists.txt#L76
> 
> I'm not super experienced with CMake (I use Meson when possible), so could you please tell me if using system speex is possible? Why isn't is treated as a normal dependency (with `target_link_libraries()`)?

I don't think there's a particular reason we build speex this way, so I'm fine with changing it to build like a normal dependency.
