### ISSUE TITLE
std::result_of has been removed in c++20

### ISSUE THREAD

**Issue by malytomas** [mozilla/cubeb#677]
There is deprecated and removed template used here:
https://github.com/mozilla/cubeb/blob/dcc5cb5c15a0ee0ea0f9f9a04d4cd48af6714501/src/cubeb_mixer.cpp#L447

The template result_of has been removed in c++20, see:
https://en.cppreference.com/w/cpp/types/result_of

**Comment by kinetiknz** [comment]
Thanks for pointing this out!  This should be addressed by #679.

**Comment by malytomas** [comment]
Thanks
