### ISSUE TITLE
Potential lack of sound and hang on stream stop if using non-native sample rate on macOS

### ISSUE THREAD

**Issue by Steveice10** [mozilla/cubeb#771]
We use Cubeb as an audio backend in the Citra emulator project: https://github.com/citra-emu/citra/blob/master/src/audio_core/cubeb_sink.cpp

For some users on macOS, Cubeb may deadlock. There is never any audio output, and when we attempt to shut the audio stream down on exit, the emulation thread stalls waiting for `cubeb_stream_stop`.

We don't make any calls to cubeb functions from within our callbacks, so I don't think that should be an issue here. This also doesn't happen for our other OpenAL based backend.

I managed to finally reproduce the issue randomly on my own Mac and can see the following traces when locked up on exit if I pause and debug threads:

Thread where `cubeb_stream_stop` is called:
```
__psynch_mutexwait 0x0000000189374524
_pthread_mutex_firstfit_lock_wait 0x00000001893af168
_pthread_mutex_firstfit_lock_slow 0x00000001893acaf8
HALB_Mutex::Lock() 0x000000018bf6e668
HALC_ProxyIOContext::StopIOProc(int (*)(unsigned int, const AudioTimeStamp *, const AudioBufferList *, const AudioTimeStamp *, AudioBufferList *, const AudioTimeStamp *, void *)) 0x000000018bbd6c80
HAL_HardwarePlugIn_DeviceStop(AudioHardwarePlugInInterface **, unsigned int, int (*)(unsigned int, const AudioTimeStamp *, const AudioBufferList *, const AudioTimeStamp *, AudioBufferList *, const AudioTimeStamp *, void *)) 0x000000018bb98afc
AudioDeviceStop_mac_imp 0x000000018bc5b380
<unknown> 0x00000001255fc934
<unknown> 0x00000001255fc8a8
<unknown> 0x00000001256fd620
AudioOutputUnitStop 0x000000018b72cd20
audiounit_stream_stop_internal(cubeb_stream *) cubeb_audiounit.cpp:2979
audiounit_stream_stop(cubeb_stream *) cubeb_audiounit.cpp:2990
cubeb_stream_stop cubeb.c:419
AudioCore::CubebSink::~CubebSink() cubeb_sink.cpp:98
AudioCore::CubebSink::~CubebSink() cubeb_sink.cpp:96
AudioCore::CubebSink::~CubebSink() cubeb_sink.cpp:96
std::default_delete::operator()[abi:v160006](AudioCore::Sink *) const unique_ptr.h:65
std::unique_ptr::reset[abi:v160006](AudioCore::Sink *) unique_ptr.h:297
std::unique_ptr::~unique_ptr[abi:v160006]() unique_ptr.h:263
std::unique_ptr::~unique_ptr[abi:v160006]() unique_ptr.h:263
AudioCore::DspInterface::~DspInterface() dsp_interface.cpp:18
AudioCore::DspHle::~DspHle() hle.cpp:450
AudioCore::DspHle::~DspHle() hle.cpp:450
AudioCore::DspHle::~DspHle() hle.cpp:450
std::default_delete::operator()[abi:v160006](AudioCore::DspInterface *) const unique_ptr.h:65
std::unique_ptr::reset[abi:v160006](AudioCore::DspInterface *) unique_ptr.h:297
Core::System::Shutdown(bool) core.cpp:573
EmuThread::run() bootmanager.cpp:133
[Inlined] $_0::operator()() const 0x000000011a157fb4
[Inlined] terminate_on_exception<…>($_0 &&) 0x000000011a157eac
QThreadPrivate::start(void *) 0x000000011a157eac
_pthread_start 0x00000001893b2034
```

Audio I/O Thread (`com.apple.audio.IOThread.client`):
```
nanov2_find_block_and_allocate 0x00000001891c76c4
nanov2_allocate_outlined 0x00000001891e5210
_dispatch_continuation_alloc_from_heap 0x00000001892348b8
dispatch_async 0x000000018920534c
audiounit_output_callback(void *, unsigned int *, const AudioTimeStamp *, unsigned int, unsigned int, AudioBufferList *) cubeb_audiounit.cpp:625
<unknown> 0x00000001256f3c44
<unknown> 0x00000001255faf78
caulk::function_ref::functor_invoker<…>(const caulk::details::erased_callable<…> &, ACAudioSpan &) 0x000000018b5d6fbc
acv2::AudioConverterChain::ObtainInput(acv2::AudioConverterBase &, unsigned int) 0x000000018b52343c
acv2::CBRConverter::ProduceOutput(ACAudioSpan &) 0x000000018b7103d0
acv2::AudioConverterChain::ObtainInput(acv2::AudioConverterBase &, unsigned int) 0x000000018b523524
acv2::Resampler2Wrapper::ProduceOutput(ACAudioSpan &) 0x000000018b6a68d0
acv2::SampleRateConverter::ProduceOutput(ACAudioSpan &) 0x000000018b4b7264
acv2::AudioConverterChain::ProduceOutput(caulk::function_ref<…>, ACBaseAudioSpan &) 0x000000018b5228f0
acv2::AudioConverterV2::fillComplexBuffer(int (*)(OpaqueAudioConverter *, unsigned int *, AudioBufferList *, AudioStreamPacketDescription **, void *), void *, unsigned int *, AudioBufferList *, AudioStreamPacketDescription *, AudioStreamPacketDependencyInfo *) 0x000000018b5d6ab0
with_resolved(OpaqueAudioConverter *, caulk::function_ref<…>) 0x000000018b5d9c48
AudioConverterFillComplexBuffer 0x000000018b5da110
<unknown> 0x00000001255fa974
<unknown> 0x00000001256f99dc
<unknown> 0x00000001255fec88
HALC_ProxyIOContext::IOWorkLoop() 0x000000018bbd3efc
invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) 0x000000018bbd13b0
HALC_IOThread::Entry(void *) 0x000000018bd50564
_pthread_start 0x00000001893b2034
```

The specific code it's at in `audiounit_output_callback` is:
```
  ...
  if (stm->shutdown) {
    ALOG("(%p) output shutdown.", stm);                               <--- This line
    audiounit_make_silent(&outBufferList->mBuffers[0]);
    return noErr;
  }
  ...
```

The audio thread seems to slightly change trace every time I resume and pause, though, so I think it's still running.

**Comment by Steveice10** [comment]
I've also noticed that with verbose logging, the callback keeps being asked for only 1 frame repeatedly.

**Comment by padenot** [comment]
We've been using a [replacement backend in Rust for macOS](https://github.com/mozilla/cubeb-coreaudio-rs/), but the C++ one should work still. I don't know if Citra has some rust already (in which case it might be an option), but fixing the C++ backend shouldn't be too hard.

I think you should attempt to remove this `ALOG` line because it's using a system message queue system https://github.com/mozilla/cubeb/blob/ed2efe22cb803f022b5a38fbbc53eec250056874/src/cubeb_audiounit.cpp#L63-L67, and I have no idea if it's OK in this context. Looks like it's probably not OK. Since this C++ backend was abandoned, cubeb has it's own async logging facilities (to be able to log from real-time code), and so this `ALOG` macro isn't needed, we can replace it with the "new" logging stuff: it's a simple interface: https://github.com/mozilla/cubeb/blob/ed2efe22cb803f022b5a38fbbc53eec250056874/src/cubeb_log.h#L52-L72. The simplest fix would probably be to just remove this logging line though.

Happy to look at a patch if you have one handy, or maybe you can try it out on your side and report back (I don't know what's Citra's policy on patching dependencies is, and this seems intermittent and not easily reproducible). I'm just about to take some time off over Christmas and NYE, but I'll look when I'm back.

**Comment by Steveice10** [comment]
Unfortunately it seems the logging stuff is a red herring, commenting out does not have any effect.

It seems that the audio unit is stuck but still looping and triggering the output callback? Basically, when this occurs:
* We'll get a few dozen calls to our output callback asking for 380 frames. This seems normal.
* At some point we'll suddenly start getting calls for just 1 frame. It remains that way from then on for subsequent calls. I've checked and the output_frames being 1 is coming from the CoreAudio audio unit into the cubeb-side audio callback.
* When we try to stop the stream, it hangs in `cubeb_stream_stop` with CoreAudio trying to lock the internal `HALB_Mutex`.

**Comment by Steveice10** [comment]
An interesing observation: we typically use the native sample rate of the emulated system, 32728, as our sample rate in the `cubeb_stream_params`. If I change that to e.g. 44100, it starts working.

**Comment by Steveice10** [comment]
If I add resampling for mismatched output sample rate like so, it works:
```diff
diff --git a/src/cubeb_audiounit.cpp b/src/cubeb_audiounit.cpp
index 37036a3..6892f69 100644
--- a/src/cubeb_audiounit.cpp
+++ b/src/cubeb_audiounit.cpp
@@ -2502,6 +2502,7 @@ audiounit_configure_output(cubeb_stream * stm)
     return CUBEB_ERROR;
   }
   stm->output_hw_rate = output_hw_desc.mSampleRate;
+  stm->output_desc.mSampleRate = stm->output_hw_rate;
   LOG("(%p) Output device sampling rate: %.2f", stm,
       output_hw_desc.mSampleRate);
   stm->context->channels = output_hw_desc.mChannelsPerFrame;
@@ -2709,11 +2710,18 @@ audiounit_setup_stream(cubeb_stream * stm)
     input_unconverted_params.rate = stm->input_hw_rate;
   }
 
+  cubeb_stream_params output_unconverted_params;
+  if (has_output(stm)) {
+    output_unconverted_params = stm->output_stream_params;
+    /* Use the rate of the output device. */
+    output_unconverted_params.rate = stm->output_hw_rate;
+  }
+
   /* Create resampler. Output params are unchanged
    * because we do not need conversion on the output. */
   stm->resampler.reset(cubeb_resampler_create(
       stm, has_input(stm) ? &input_unconverted_params : NULL,
-      has_output(stm) ? &stm->output_stream_params : NULL, target_sample_rate,
+      has_output(stm) ? &output_unconverted_params : NULL, target_sample_rate,
       stm->data_callback, stm->user_ptr, CUBEB_RESAMPLER_QUALITY_DESKTOP,
       CUBEB_RESAMPLER_RECLOCK_NONE));
   if (!stm->resampler) {
```

So it seems there's something wrong when a non-native sample rate is supplied to the Audio Unit.

**Comment by padenot** [comment]
Ah yes, I'd believe that, it's not exactly common outside of emulation and that's a pretty weird SR.

We could certainly take this patch. `cubeb` allow getting the "preferred" sample-rate using the API, and it's common for users to want that (since you can bypass the resampler and get lower latency on some platforms).

**Comment by Steveice10** [comment]
Thanks, I've opened a pull request for this here if you'd like to take a look: https://github.com/mozilla/cubeb/pull/772

**Comment by Steveice10** [comment]
Any updates on this / the linked PR?

**Comment by padenot** [comment]
Absolutely none, this was swallowed by the end-of-year-vacation vortex that made me forget about various issues.

Thanks for pinging me and sorry for the delay, I'll look at it now.
