### ISSUE TITLE
When using the USB sound card in duplex mode, audio recording has interruptions

### ISSUE THREAD

**Issue by Monsterovich** [mozilla/cubeb#773]
The problem appears in recently built Firefox 121 only after refresh of the page, and sometimes immediately. Chrome-based apps don't have this issue. I'm using pipewire 1.0 via pulse.

See the video: 

[2023-12-18_17-18-15.mkv.zip](https://github.com/mozilla/cubeb/files/13757438/2023-12-18_17-18-15.mkv.zip)

~~This problem can be avoided by doing this:~~

```
pactl load-module module-null-sink sink_name=virtmic sink_properties=device.description=Virtual_Microphone_Sink
```

~~If you make the sound output to a virtual device that is linked to a real device. Then the problem will disappear.~~

![image](https://github.com/mozilla/cubeb/assets/3750982/2cf0ff48-91d4-495c-80e7-b4f51329619a)

**UPDATE:** jack backend works fine in duplex mode.

**Comment by padenot** [comment]
Please open bugs on [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Audio%2FVideo%3A%20cubeb) for Firefox bugs (except if you can reproduce with just cubeb of course). This is likely related to thread priorities. In Firefox, you can get nice logging following (including info about real-time audio) by following https://paul.cx/public/about-logging-presentation.webm and choosing the `Media` preset.
