### ISSUE TITLE
Cannot build package stdlib.h missing

### ISSUE THREAD

**Issue by JAGGYWAGGY88** [mozilla/cubeb#787]
Running Steam OS 3.5

Following the build directions in INSTALL.md after cloning the git repo. 

On the following command:

`cmake --build ./build`

I receive the following error:

```
[  2%] Building C object CMakeFiles/speex.dir/subprojects/speex/resample.c.o
/home/deck/cubeb/subprojects/speex/resample.c:65:10: fatal error: stdlib.h: No such file or directory
   65 | #include <stdlib.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/speex.dir/build.make:76: CMakeFiles/speex.dir/subprojects/speex/resample.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:148: CMakeFiles/speex.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by padenot** [comment]
Please follow this: https://www.reddit.com/r/SteamDeck/comments/t92ozw/for_compiling_c_code/. You're missing essential components to compile C code, and that needs fixing first.
